/**
 * Template detection, based on studying the 81 real reports in use:
 * - carfax-html: official Carfax report markup (`detailed-history-row`,
 *   `common-section-row-heading`, `history-overview-main-text` classes).
 *   Identical whether it comes straight from carfax.com or through the
 *   cheapcarfax.net reseller — same HTML, different hostname.
 * - carfax-pdf: text-based Carfax PDF ("CARFAX Vehicle History Report"
 *   banner), whether generated by the globalvin provider or a manual
 *   upload — same layout either way.
 * - autocheck-html: Experian AutoCheck HTML ("Vehicle History at a Glance",
 *   `owner-card-cell-border-right`, AutoCheck Score widget).
 * - autocheck-pdf: text-based AutoCheck PDF ("Experian AutoCheck Report").
 * - unknown: anything else (scanned/garbage uploads, unrelated documents).
 */
export type ParserTemplate = 'carfax-html' | 'carfax-pdf' | 'autocheck-html' | 'autocheck-pdf' | 'unknown';

export function detectTemplate(
  text: string,
  format: 'html' | 'pdf',
  reportTypeHint?: string | null,
): ParserTemplate {
  if (format === 'html') {
    if (/detailed-history-row|common-section-row-heading|history-overview-main-text/.test(text)) {
      return 'carfax-html';
    }
    if (/Vehicle History at a Glance|owner-card-cell-border-right|AutoCheck Score/i.test(text)) {
      return 'autocheck-html';
    }
    return 'unknown';
  }

  // PDF: text already extracted (pdf-parse). Scanned/near-empty PDFs are
  // caught upstream by the caller (< 200 chars => 'unsupported' regardless
  // of template).
  if (/CARFAX Vehicle History Report/i.test(text)) {
    return 'carfax-pdf';
  }
  if (/Experian AutoCheck|AutoCheck Report/i.test(text)) {
    return 'autocheck-pdf';
  }
  // Fall back to the requested report type only when we have *some*
  // vehicle-history-shaped signal; pure garbage (emails, invoices, random
  // web pages saved as PDF) must stay 'unknown' so it's marked unsupported.
  if (/Vehicle History Report|Title History|Odometer Check/i.test(text)) {
    if (reportTypeHint === 'autocheck') return 'autocheck-pdf';
    return 'carfax-pdf';
  }
  return 'unknown';
}
